import { DemoSplit } from '../components/DemoSplit';
import { ReactCarousel } from './React components/CarouselReact';
import { CssCarousel } from './Inbuilt components/CarouselCss';

export function CarouselDemo() {
  return (
    <DemoSplit
      reactSide={<ReactCarousel />}
      cssSide={<CssCarousel />}
      reactNotes={
        <ul>
          <li>
            State, transforms, click handlers, dot sync, ARIA wiring — all
            written by hand.
          </li>
          <li>
            Touch/swipe/inertia and keyboard navigation would each need extra
            code (or a library).
          </li>
        </ul>
      }
      cssNotes={
        <ul>
          <li>
            Zero JS. <code>scroll-snap-type</code> + native momentum scroll,
            wheel, swipe and keyboard.
          </li>
          <li>
            <code>::scroll-button(left/right)</code> renders the arrow
            controls; <code>scroll-marker-group</code> + <code>::scroll-marker</code>{' '}
            renders the dots — all generated by the browser.
          </li>
          <li>
            The active dot uses <code>:target-current</code>, set automatically
            as the user scrolls.
          </li>
        </ul>
      }
    />
  );
}
